### ISSUE TITLE
The Url

### ISSUE THREAD

**Issue by gngchrs** [kevgathuku/droplinks#2]
Tested the application. However it doesn't accept the file:// protocol .. only works with http links. Had to use http://localhost to get a file from my pc. 
I haven't worked with the dropbox api yet, so I don't know if its a restriction

**Comment by kevgathuku** [comment]
@gangachris the point of the application is to avoid having to download large files from the Internet before saving them to Dropbox. For a local file, it's much easier to upload to Dropbox directly. However, if you think this feature would be useful, please feel free to send a pull request.
